### ISSUE TITLE
Error compiling first example in VS Code

### ISSUE THREAD

**Issue by tom-van-acker** [holgerflick/tmswebcore2nd#1]
I'am using VS Code with the TMS Web Core extension. I just cloned the repo and tried to compile the first example. This gives me the error: 
Pas2JS Compiler version 2.3.1 [2023/03/06] for Win64 x86_64
c:\Dev\tmswebcore\tmswebcore2nd\Examples\02.03 First App\Unit1.pas (110, 14) Error: identifier not found "Width"

I found that when removing the width and height from the TWebTimer in the dfm, the error disappeared.

**Comment by holgerflick** [comment]
Thank you for your report. That project has been created before the VSC version existed and I had never tested to load it there. I will remove the two properties. I have also confirmed if you create the project "from scratch" that everything works as expected and described in the book.
