### ISSUE TITLE
Submit Form button not working

### ISSUE THREAD

**Issue by raelb** [holgerflick/tmswebcore2nd#2]
Hi,
I wanted to send you a message, however the `Submit Form` button is not working on holgerscode.com.
Tried on Firefox and Chrome.

**Comment by holgerflick** [comment]
Thank you for your message. I can confirm it stopped working. Thank you for the info! I'll try to fix it asap.

**Comment by raelb** [comment]
Holger, is there an email address I can contact you with?

**Comment by holgerflick** [comment]
Yes, it is in all my videos at the beginning. Use holger(at)flixengineering.com .
